apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - mongo.yaml
  - kafka.yaml
  - kafka-ui.yaml
  - rest.yaml
  - webui.yaml
  - ingress.yaml
  - kafka-stream.yaml
