apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: javi
  labels:
    app.kubernetes.io/name: javi
    app.kubernetes.io/component: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark
  namespace: javi
  labels:
    app.kubernetes.io/name: javi
    app.kubernetes.io/component: spark
rules:
  - apiGroups: [""]
    resources: [pods, services, configmaps]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark
  namespace: javi
  labels:
    app.kubernetes.io/name: javi
    app.kubernetes.io/component: spark
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: javi
roleRef:
  kind: Role
  name: spark
  apiGroup: rbac.authorization.k8s.io
