addSbtPlugin("org.scoverage"   % "sbt-scoverage" % "2.4.4")
addSbtPlugin("org.scoverage"   % "sbt-coveralls" % "1.3.11")
addSbtPlugin("com.eed3si9n"    % "sbt-assembly"  % "2.2.0")
addSbtPlugin("io.spray"        % "sbt-revolver"  % "0.10.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"   % "0.4.7")
